LABELS = ["datetime", "duration", "geographical_region", "border", "third-party_actor", "power", "voltage_level", "voltage", "infrastructure", "substation", "network_event", "center", "operation", "external_event", "criticality",
          "event_impact", "moment", "event", "country", "value", "actor", "app", "TOPOLOGY", "STUDY", "LINE", "OPERATING CONDITIONS", "TRANSIT", "DECISION", "LIMIT", "OPERATING MODE", "DATA", "IT ISSUE", "TOOL ACTION", "TO DO", "CALL"]

ABREVIATIONS = {
    # "RACR": "Retour à la conduite des réseaux",
    # "RDCR": "Retrait de la conduite des réseaux",
    # "TIR": "Thermographie infrarouge",
    # "PO": "Poste opérateur",
    # "RSD": "Régime surveillance dispatching",
    # "SUAV": "Sous tension à vide",
    # "MNV": "Manoeuvre",
    # "PF": "Point figé",
    # "CSS": "Central sous station (SNCF)",
    # "GEH": "Groupe exploitation hydraulique",
    # "PDM": "Personnel de manoeuvre",
    # "SMACC": "Système avancé pour la commande de la compensation",
    # "HO": "Heures ouvrées",
    # "BR": "Bâtiment de relayage",
    # "GT": "Groupe de traction",
    # "TST": "Travaux sous tensions",
    # "CCO": "Chargé de conduite",
    # "FDE": "Filet d'essai",
    # "DIFFB": "Protection différentielle de barre",
    # "RADA": "Retrait agile suite à détection d'anomalie",
    # "TR": "Transformateur",
    # "RA": "Réenclencheur automatique",
    # "CTS": "Cycle triphasé supplémentaire",
    # "CEX": "Chargé d'exploitation",
    # "COSE": "Centre opérationnel du système électrique",
    # "COSE-P": "Centre opérationnel du système électrique de Paris"
}
